#! /bin/bash
mkdir MapReduce_Project_Master/lib/
ant -f build-master.xml jar

mkdir MapReduce_Project_Slave/lib/
mkdir MapReduce_Project_UserTest/lib/

cp master.jar ./MapReduce_Project_Slave/lib/master.jar
cp master.jar ./MapReduce_Project_UserTest/lib/master.jar

ant -f build-slave.xml jar
ant -f build-user.xml jar

rm -r *obj
rm master.jar
